
spring:
  application:
    name: "SpringBoot Rest API"
  profiles:
    active:
      - local

server:
  servlet:
    context-path: "/"
  port: 8080

logging: 
    level: 
      ROOT: DEBUG

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info"