
spring:
  application:
    name: "SpringBoot Rest API"
  profiles:
    active:
      - local
      
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

server:
  servlet:
    context-path: "/"
  port: 8080

logging: 
    level: 
      ROOT: DEBUG

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info"